### ISSUE TITLE
FC...

### ISSUE THREAD

**Issue by alpsehic** [PaperAirplane-Dev-Team/SwipeBack#2]
Crashes just after initial loading of installed application list...

**Comment by alpsehic** [comment]
Samsung Note 2, Stock ROM...

**Comment by PeterCxy** [comment]
Every time?

**Comment by alpsehic** [comment]
Yes, unfortunately...

Thanks...

**Comment by PeterCxy** [comment]
Could you obtain a logcat? I am confused....

**Comment by alpsehic** [comment]
Here it is:
Process: info.papdt.swipeback, PID: 11517

java.lang.RuntimeException: An error occured while executing doInBackground()

```
at android.os.AsyncTask$3.done(AsyncTask.java:300)

at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)

at java.util.concurrent.FutureTask.setException(FutureTask.java:222)

at java.util.concurrent.FutureTask.run(FutureTask.java:242)

at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

at java.lang.Thread.run(Thread.java:841)
```

Caused by: java.lang.OutOfMemoryError

```
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)

at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:683)

at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:513)

at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)

at android.content.res.Resources.loadDrawable(Resources.java:3436)

at android.content.res.Resources.getDrawable(Resources.java:1909)

at android.content.res.XResources.getDrawable(XResources.java:521)

at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:729)

at android.content.pm.PackageItemInfo.loadIcon(PackageItemInfo.java:167)

at android.app.ApplicationPackageManager.getApplicationIcon(ApplicationPackageManager.java:792)

at info.papdt.swipeback.ui.app.PerAppFragment.loadData(PerAppFragment.java:54)

at info.papdt.swipeback.ui.base.BaseListFragment$LoadDataTask.doInBackground(BaseListFragment.java:83)

at info.papdt.swipeback.ui.base.BaseListFragment$LoadDataTask.doInBackground(BaseListFragment.java:69)

at android.os.AsyncTask$2.call(AsyncTask.java:288)

at java.util.concurrent.FutureTask.run(FutureTask.java:237)

... 4 more
```

[ 03-31 13:02:09.341  2488:11622 E/android.os.Debug ]

!@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error

[ 03-31 13:02:09.401 11517:11517 E/WindowManager ]

android.view.WindowLeaked: Activity info.papdt.swipeback.ui.base.GlobalActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42c00f58 V.E..... R....... 0,0-684,280} that was originally added here

```
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:467)

at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:267)

at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)

at android.app.Dialog.show(Dialog.java:289)

at info.papdt.swipeback.ui.base.BaseListFragment$LoadDataTask.onPreExecute(BaseListFragment.java:78)

at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:587)

at android.os.AsyncTask.execute(AsyncTask.java:535)

at info.papdt.swipeback.ui.base.BaseListFragment.onAttach(BaseListFragment.java:37)

at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:849)

at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)

at android.app.BackStackRecord.run(BackStackRecord.java:684)

at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)

at android.app.Activity.performStart(Activity.java:5460)

at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)

at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)

at android.app.ActivityThread.access$900(ActivityThread.java:175)

at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:146)

at android.app.ActivityThread.main(ActivityThread.java:5602)

at java.lang.reflect.Method.invokeNative(Native Method)

at java.lang.reflect.Method.invoke(Method.java:515)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)

at dalvik.system.NativeStart.main(Native Method)
```

[ 03-31 13:02:10.456  2488: 2602 E/ViewRootImpl ]

sendUserActionEvent() mView == null

**Comment by alpsehic** [comment]
Btw, I am on Xposed 2.7 experimental 1...

**Comment by seasonyuu** [comment]
What's the android version of your device?

**Comment by alpsehic** [comment]
4.4.2...

**Comment by PeterCxy** [comment]
Seems like an amazing error. I will try to figure out why - but it really seems like an internal error in Android.

**Comment by seasonyuu** [comment]
How many apps have you installed?

**Comment by alpsehic** [comment]
Let's say like 150 apps. But I've faced similar error on some Xposed modules which also try to list all installed hands like XHaloFloatingWindow. But on the other hand, most apps which try to list the installed apps cope with that without any crash like AutomateIt or like Xposed modules App settings, MW Apps Manager, XInternalSD etc., maybe it depends on the method how you do try to get the list of installed apps...

Thanks a lot...

**Comment by fython** [comment]
这似乎是加载应用的图标时出错？
It seems to fail to load the icons of apps....

**Comment by PeterCxy** [comment]
I am going to try to fix this today.

**Comment by alpsehic** [comment]
It has been fixed, thanks guys...
