### ISSUE TITLE
发现我可以直接在这里发给你

### ISSUE THREAD

**Issue by seasonyuu** [PaperAirplane-Dev-Team/SwipeBack#3]
java.lang.RuntimeException: Unable to start activity ComponentInfo{info.papdt.swipeback/info.papdt.swipeback.ui.base.GlobalActivity}: android.view.InflateException: Binary XML file line #11: Error inflating class java.lang.reflect.Constructor
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5034)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #11: Error inflating class java.lang.reflect.Constructor
            at android.preference.GenericInflater.createItem(GenericInflater.java:397)
            at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
            at info.papdt.swipeback.ui.base.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:16)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:690)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1449)
            at android.app.Activity.performStart(Activity.java:5255)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5034)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.preference.GenericInflater.createItem(GenericInflater.java:383)
            at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
            at info.papdt.swipeback.ui.base.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:16)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:690)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1449)
            at android.app.Activity.performStart(Activity.java:5255)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5034)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at android.preference.MultiSelectListPreference.onGetDefaultValue(MultiSelectListPreference.java:212)
            at android.preference.Preference.<init>(Preference.java:268)
            at android.preference.DialogPreference.<init>(DialogPreference.java:69)
            at android.preference.DialogPreference.<init>(DialogPreference.java:90)
            at android.preference.MultiSelectListPreference.<init>(MultiSelectListPreference.java:49)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.preference.GenericInflater.createItem(GenericInflater.java:383)
            at android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
            at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
            at android.preference.GenericInflater.rInflate(GenericInflater.java:481)
            at android.preference.GenericInflater.inflate(GenericInflater.java:326)
            at android.preference.GenericInflater.inflate(GenericInflater.java:263)
            at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
            at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:285)
            at info.papdt.swipeback.ui.base.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:16)
            at android.app.Fragment.performCreate(Fragment.java:1678)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:859)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
            at android.app.BackStackRecord.run(BackStackRecord.java:690)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1449)
            at android.app.Activity.performStart(Activity.java:5255)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5034)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by PeterCxy** [comment]
真瞎……
